# Generated by Django 4.2.dev20220526083951 on 2022-07-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_img',
        ),
    ]
