# Generated by Django 4.2.dev20220526083951 on 2022-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile-pics'),
        ),
    ]
