# Generated by Django 4.2.dev20220526083951 on 2022-07-29 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_description', models.TextField(default='Put Task Description')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('task_assignedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_to_user', to=settings.AUTH_USER_MODEL)),
                ('task_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
