# Generated by Django 4.2.dev20220526083951 on 2022-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_img',
            field=models.ImageField(blank=True, default='default-book-cover.jpg', null=True, upload_to='tasks-pics'),
        ),
    ]
