# Generated by Django 4.2.dev20220526083951 on 2022-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_img',
            field=models.ImageField(blank=True, default='default-book-cover.png', null=True, upload_to='tasks-pics'),
        ),
    ]
