# Generated by Django 4.2.dev20220526083951 on 2022-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_task_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_group',
            field=models.CharField(default='', max_length=255),
        ),
    ]
