# Generated by Django 4.2.dev20220526083951 on 2022-08-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_board_board_members_board_board_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_tasks',
            field=models.ManyToManyField(blank=True, related_name='board_tasks', to='tasks.tasks'),
        ),
    ]
